# On push

name: Fetch
on: [push]

jobs:

  fetch:
    runs-on: ubuntu-latest
    steps:

      # Step 1
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2
      - name: Get Data
        run: |
          curl 'https://api.airtable.com/v0/app5QplNRBqYTwfDe/Imported%20table' \
              --header 'Authorization: Bearer ${{ secrets.AIRTABLE_KEY }}' > data.json
          date > last-updated.txt
          

      # Step 3
      - name: Push Data
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add -A
          git commit -am "Fetch New Data"
          git push
         
